name: Build fib-pay-mcp
on: [push, pull_request]
jobs:
  build:
    name: fib-pay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 21
      - name: Build
        run: gradle build -x test
      - name: Upload build artifact
        if: github.ref_name == 'master'
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./build/libs/*.jar
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'master'
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./build/libs

      - name: Get latest release
        id: get_release
        uses: joutvhu/get-release@v1
        with:
          latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git tag
        run: |
          TAG_NAME=$(date +'%Y%m%d-%H%M%S')
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Upload artifact to latest release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          files: ./build/libs/*.jar