name: Build fib-pay-mcp
on: [push, pull_request]
jobs:
  build:
    name: fib-pay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 21
      - name: Build
        run: mvn -f pom.xml clean package -DskipTests
      - name: Upload build artifact
        if: github.ref_name == 'master'
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./target/*.jar